#ifndef SNAKE_INPUT_H
#define SNAKE_INPUT_H
/*
    Placeholder for OS-independent key handling
    Renames keycodes to KEY_ instead of OS specific naming.
    Only keys that should be common across all OS will be included here.
*/

#ifdef _WIN32

#include <winuser.h>
#define KEYINPUT_LBUTTON VK_LBUTTON
#define KEYINPUT_RBUTTON VK_RBUTTON
#define KEYINPUT_CANCEL VK_CANCEL
#define KEYINPUT_MBUTTON VK_MBUTTON
#define KEYINPUT_XBUTTON1 VK_XBUTTON1
#define KEYINPUT_XBUTTON2 VK_XBUTTON2
#define KEYINPUT_BACKSPACE VK_BACK
#define KEYINPUT_TAB VK_TAB
#define KEYINPUT_CLEAR VK_CLEAR
#define KEYINPUT_RETURN VK_RETURN
#define KEYINPUT_SHIFT VK_SHIFT
#define KEYINPUT_CONTROL VK_CONTROL
#define KEYINPUT_ALT VK_MENU
#define KEYINPUT_PAUSE VK_PAUSE
#define KEYINPUT_CAPITAL VK_CAPITAL
#define KEYINPUT_ESCAPE VK_ESCAPE
#define KEYINPUT_SPACE VK_SPACE
#define KEYINPUT_PGUP VK_PRIOR
#define KEYINPUT_PGDOWN VK_NEXT
#define KEYINPUT_END VK_END
#define KEYINPUT_HOME VK_HOME
#define KEYINPUT_LEFT VK_LEFT
#define KEYINPUT_UP VK_UP
#define KEYINPUT_RIGHT VK_RIGHT
#define KEYINPUT_DOWN VK_DOWN
#define KEYINPUT_SELECT VK_SELECT
#define KEYINPUT_PRINT VK_PRINT
#define KEYINPUT_EXECUTE VK_EXECUTE
#define KEYINPUT_SNAPSHOT VK_SNAPSHOT
#define KEYINPUT_INSERT VK_INSERT
#define KEYINPUT_DELETE VK_DELETE
#define KEYINPUT_HELP VK_HELP
#define KEYINPUT_LWIN VK_LWIN
#define KEYINPUT_RWIN VK_RWIN
#define KEYINPUT_APPS VK_APPS
#define KEYINPUT_SLEEP VK_SLEEP
#define KEYINPUT_NUMPAD0 VK_NUMPAD0
#define KEYINPUT_NUMPAD1 VK_NUMPAD1
#define KEYINPUT_NUMPAD2 VK_NUMPAD2
#define KEYINPUT_NUMPAD3 VK_NUMPAD3
#define KEYINPUT_NUMPAD4 VK_NUMPAD4
#define KEYINPUT_NUMPAD5 VK_NUMPAD5
#define KEYINPUT_NUMPAD6 VK_NUMPAD6
#define KEYINPUT_NUMPAD7 VK_NUMPAD7
#define KEYINPUT_NUMPAD8 VK_NUMPAD8
#define KEYINPUT_NUMPAD9 VK_NUMPAD9
#define KEYINPUT_MULTIPLY VK_MULTIPLY
#define KEYINPUT_ADD VK_ADD
#define KEYINPUT_SEPARATOR VK_SEPARATOR
#define KEYINPUT_SUBTRACT VK_SUBTRACT
#define KEYINPUT_DECIMAL VK_DECIMAL
#define KEYINPUT_DIVIDE VK_DIVIDE
#define KEYINPUT_F1 VK_F1
#define KEYINPUT_F2 VK_F2
#define KEYINPUT_F3 VK_F3
#define KEYINPUT_F4 VK_F4
#define KEYINPUT_F5 VK_F5
#define KEYINPUT_F6 VK_F6
#define KEYINPUT_F7 VK_F7
#define KEYINPUT_F8 VK_F8
#define KEYINPUT_F9 VK_F9
#define KEYINPUT_F10 VK_F10
#define KEYINPUT_F11 VK_F11
#define KEYINPUT_F12 VK_F12
#define KEYINPUT_F13 VK_F13
#define KEYINPUT_F14 VK_F14
#define KEYINPUT_F15 VK_F15
#define KEYINPUT_F16 VK_F16
#define KEYINPUT_F17 VK_F17
#define KEYINPUT_F18 VK_F18
#define KEYINPUT_F19 VK_F19
#define KEYINPUT_F20 VK_F20
#define KEYINPUT_F21 VK_F21
#define KEYINPUT_F22 VK_F22
#define KEYINPUT_F23 VK_F23
#define KEYINPUT_F24 VK_F24
#define KEYINPUT_NUMLOCK VK_NUMLOCK
#define KEYINPUT_SCROLL VK_SCROLL
#define KEYINPUT_LSHIFT VK_LSHIFT
#define KEYINPUT_RSHIFT VK_RSHIFT
#define KEYINPUT_LCONTROL VK_LCONTROL
#define KEYINPUT_RCONTROL VK_RCONTROL
#define KEYINPUT_LMENU VK_LMENU
#define KEYINPUT_RMENU VK_RMENU

#endif /* _WIN32 */

#endif /* SNAKE_INPUT_H */